export const listOfSkills = [
  {
    key: 'HTML5',
    name: 'HTML5',
    type: 'Programming',
    value: 90,
  },
  {
    key: 'CSS3',
    name: 'CSS3',
    type: 'Programming',
    value: 80,
  },
  {
    key: 'JavaScript',
    name: 'JavaScript',
    type: 'Programming',
    value: 70,
  },
  {
    key: 'React',
    name: 'React',
    type: 'Programming',
    value: 60,
  },
  // {
  //   key: 'Vue.js',
  //   name: 'Vue.js',
  //   type: 'Programming',
  //   value: 50,
  // },
  {
    key: 'Next.js',
    name: 'Next.js',
    type: 'Programming',
    value: 25,
  },
  {
    key: 'Bulma.io',
    name: 'Bulma.io',
    type: 'Programming',
    value: 63,
  },
  {
    key: 'Bootstrap',
    name: 'Bootstrap',
    type: 'Programming',
    value: 45,
  },

  {
    key: 'PHP',
    name: 'PHP',
    type: 'Programming',
    value: 40,
  },
  {
    key: 'MySQL',
    name: 'MySQL',
    type: 'Programming',
    value: 30,
  },
  {
    key: 'C',
    name: 'C',
    type: 'Programming',
    value: 30,
  },
  {
    key: 'Git',
    name: 'Git',
    type: 'Programming',
    value: 80,
  },
  {
    key: 'English',
    name: 'English',
    type: 'Languages',
    value: 95,
  },
  {
    key: 'Portuguese',
    name: 'Portuguese',
    type: 'Languages',
    value: 99,
  },
  {
    key: 'Spanish',
    name: 'Spanish',
    type: 'Languages',
    value: 55,
  },
  {
    key: 'Mandarin',
    name: 'Mandarin',
    type: 'Languages',
    value: 45,
  },
  {
    key: 'Teamwork',
    name: 'Teamwork',
    type: 'Skills',
    value: 87,
  },
  {
    key: 'Time management',
    name: 'Time management',
    type: 'Skills',
    value: 95,
  },
  {
    key: 'Agile and Scrum',
    name: 'Agile and Scrum',
    type: 'Skills',
    value: 92,
  },
  {
    key: 'Leadership',
    name: 'Leadership',
    type: 'Skills',
    value: 79,
  },
  {
    key: 'Critical thinking',
    name: 'Critical thinking',
    type: 'Skills',
    value: 84,
  },
  {
    key: 'Delegation',
    name: 'Delegation',
    type: 'Skills',
    value: 92,
  },
  {
    key: 'Creative',
    name: 'Creative',
    type: 'Skills',
    value: 82,
  },
];
